### ISSUE TITLE
Sort derives

### ISSUE THREAD

**Issue by ayazhafiz** [rust-dev-tools/fmt-rfcs#154] opened 2020-07-03 14:47 UTC
See https://github.com/rust-lang/rustfmt/issues/4112 and https://github.com/rust-lang/rustfmt/issues/1867 for more context and discussion.

This rfc proposes the sorting of items listed in a derive attribute. Sorting derives keeps uniformity in a project, since derive attributes can often list many items, and expecting a consistent order helps readers more quickly scan an item's derives.

## Alternatives

These three alternatives are taken from https://github.com/rust-lang/rustfmt/issues/4112; here I enumerate them and provide what I think are advantages/disadvantages of each.

### (1) Alphabetical sorting

```rust
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
```

Advantages:
- Easy to read; it is quick to figure out where a derive is/should be given the placement of other derives
- Trivial to implement

Disadvantages:
- Relational grouping of derives is lost. For example, `Eq` and `PartialEq` are often derived together and placed adjacently, implicitly implying a relationship; such a relationship cannot be preserved with alphabetical ordering.

### (2) "Canonical" sorting

Specifically, by "canonical" sorting I mean the sorting of derivable `std` traits in the order they are listed in the [rust API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html). Traits not included in that list are ordered alphabetically at the end of the derive list.

```rust
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Display, Default, CustomTrait, CrateSpecificTrait)]
```

Advantages:
- Preserves implicit relationships among "common" (std) traits.
- Somewhat complies with the convention already stated in the API guidelines.

Disadvantages:
<ul>
<li>
Having two different sortings merged as one could be confusing, particularly when custom traits are derived. It may be harder to scan for custom traits in this sorting scenario, since they are always at the end of the "common" list, but what that end is depends on how many "common" traits were derived, and is thus not consistent.
</li>
<li>
We can only get halfway with preserving implicit relationships this way. Implicit relationships between custom derives cannot be preserved; for example, given

```rust
#[derive(CustomDebug, Injective, Surjective, Bijective)]
```

a tool like rustfmt cannot (consistently) deduce that the latter three traits are related, and would format the derive as

```rust
#[derive(Bijective, CustomDebug, Injective, Surjective)]
```

I'm not convinced that only partially supporting implicit relationships is a bad thing, but this is important to mention.
</li>
<li>
If the list in the API guidelines doc is ever amended, the order in rustfmt would have to be amended as well. (More insight from the docs/libraries team is wanted here wrt if this would actually happen). Alternatively, rustfmt could copy the order and adopt it independently.
</li>
</ul>

### (3) Sort by resolved trait path

Given the following derive

```rust
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Serialize,
    Deserialize,
    TypeGenerator,
    CopyGetters,
    Getters,
    Builder,
)]
struct S;
```

try to format the derives alphabetically by their full path
> that is, by sorting
>
> ```rust
> #[derive(
>     std::fmt::Debug,
>     std::clone::Clone,
>     std::cmp::PartialEq,
>     std::cmp::Eq,
>     std::cmp::PartialOrd,
>     std::cmp::Ord,
>     std::hash::Hash,
>     serde::ser::Serialize,
>     serde::de::Deserialize,
>     bolero::generator::TypeGenerator,
>     getset::CopyGetters,
>     getset::Getters,
>     derive_builder::Builder,
> )]
> struct S;
> ```
> 
> into
> 
> ```rust
> #[derive(
>     bolero::generator::TypeGenerator,
>     derive_builder::Builder,
>     getset::CopyGetters,
>     getset::Getters,
>     serde::de::Deserialize,
>     serde::ser::Serialize,
>     std::clone::Clone,
>     std::cmp::Eq,
>     std::cmp::Ord,
>     std::cmp::PartialEq,
>     std::cmp::PartialOrd,
>     std::fmt::Debug,
>     std::hash::Hash,
> )]
> struct S;
> ```

So the original example would be sorted as

```rust
#[derive(
    TypeGenerator,
    Builder,
    CopyGetters,
    Getters,
    Deserialize,
    Serialize,
    Clone,
    Eq,
    Ord,
    PartialEq,
    PartialOrd,
    Debug,
    Hash,
)]
struct S;
```

Advantages:

- Preserves crate relationships

Disadvantages:

- This is probably not feasible to implement, since tools like rustfmt are generally purely syntactic. Implementing this kind of sorting would require name resolution, which is outside the scope of work tools like rustfmt should be doing. Asking rustfmt to include name resolution would incur a significant runtime and complexity penalty, and fail for non-resolvable names (rustfmt should still be able to format such names if they are well-formed).

## Risks

- It was previously mentioned that sorting derives may lead to a failure in compilation because derived traits can only see the traits ahead of them. While this may have been true in the past, it doesn't appear to be the case today (or at least its consequences don't seem to be). Input from someone with more insight is needed to verify this (maybe someone who works on the trait solver?).

## Suggestion

My suggestion is to provide options (1): Alphabetical Sorting and (2): "Canonical" Sorting in rustfmt. I hypothesize that the most common use case is to only use std-provided derivable traits; in this situation, "Canonical" sorting is likely the nicest alternative for a user due to its preservation of implicit relationships. For more complex use cases, alphabetical sorting may be more readable and consistent across a code base.

As for the rust style guide, I suggest specifying that derives should be sorted alphabetically.

This is just my opinion; more insights are requested.

**Comment by joshtriplett** [comment] 2020-07-04 17:32
The style team discussed this when initially developing the default Rust style and style guide. Our concern at that time was partly that derives are not always reorderable (because a proc-macro derive might care what other derives go inside/outside), and partly that people do sometimes list derives in a specific order for a logical reason.

I'm not opposed to changing this, but we'd need to address those points.

**Comment by ayazhafiz** [comment] 2020-07-14 05:13
> derives are not always reorderable (because a proc-macro derive might care what other derives go inside/outside)

Do you know who can be contacted for more insight on this? I have no knowledge of how ordering derives may make a semantic difference for proc macros, and cannot seem to find any resources online.

> partly that people do sometimes list derives in a specific order for a logical reason

This is a good point. I think a reasonable solution would be to treat groups of derives like [imports](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/items.md#ordering-of-imports) are treated. That is, traits in a single `#[derive]` clauses are sorted by some strategy, but traits across derive clauses are not merged.

**Comment by joshtriplett** [comment] 2020-07-14 06:18
@ayazhafiz 
> Do you know who can be contacted for more insight on this? I have no knowledge of how ordering derives may make a semantic difference for proc macros, and cannot seem to find any resources online.

Try the rust-lang Zulip under t-lang or t-compiler, or internals.rust-lang.org, and in either case mention specifically that you're seeking examples where a proc-macro derive could be order-dependent relative to other derives.

**Comment by Luro02** [comment] 2020-08-11 07:16
> I have no knowledge of how ordering derives may make a semantic difference for proc macros, and cannot seem to find any resources online.

The problem is that proc-macros can do whatever they want at compile-time. For example one derive macro could write something to a file and the other would read it (if they were reordered the file might not exist), but to me this seems like an anti-pattern, because proc-macros are designed to be order independent (you can not infer which other traits have been derived from a proc-macro)

**Comment by calebcartwright** [comment] 2021-12-08 00:15
Going to close this. I appreciate the recurring interest in this and that many folks could leverage the feature without running into issues. However, we can't categorically prescribe something within the style guide that could knowingly be problematic and a subtle source of bugs, and similarly I don't want to have a feature in rustfmt that could cause such bugs.

**Closed by calebcartwright** 2021-12-08 00:15 UTC

**Comment by MixusMinimax** [comment] 2024-03-13 16:50
I agree with mgeisler, but I would extend it to this:

from the derive token tree, perform a take_while that only accepts well-known derives. Then, these can be sorted.

let's say, derives starting with `A` are well-known, as in they are part of the official rust documentation.

Then, the following example:

```rust
#[derive(A1, A2, A7, A4, B1, B4, B2, A3)]
```

Will only consider A1, A2, A7, and A4, and sort those.

This would guarantee that there can not be any weird bugs, as these derives are well understood, and absolutely none of the third-party derives are affected in any way.

**Comment by maksym-arutyunyan** [comment] 2024-09-01 08:41
Hi all!

In 2017, a [request](https://github.com/rust-lang/rustfmt/issues/1867) was made about handling the order of Rust derive traits in `rustfmt`. This was revisited in 2020 and [closed](https://github.com/rust-lang/style-team/issues/154#issuecomment-988365729) with the reasoning that enforcing a specific order could introduce subtle bugs.

It’s now 2024, and I'm unsure if this reasoning still applies. I have created a [simple example](https://github.com/maksym-arutyunyan/keepsorted/pull/24) with two traits, `First` and `Second`, where `Second` depends on `First`. In my [tests](https://github.com/maksym-arutyunyan/keepsorted/blob/41f56184d680b248bd8dfe7be1156a0d78d15d0f/research/derive_order/README.md?plain=1#L32), both derive orders worked fine, and I couldn’t find evidence that the order is crucial.

1) Could you please provide an update on whether the order of derive traits is still considered important? If it is, could you provide a clear example demonstrating why?

2) If the order is no longer important, could you consider reopening this feature request?

For now, I’ve created a tool to help maintain derive order until this feature is possibly implemented in `rustfmt`. You can find it [here](https://github.com/maksym-arutyunyan/keepsorted/pull/23).

Thank you!

UPD: for one-time modifications one can use [sort-derive-traits.github.io](https://sort-derive-traits.github.io)

**Comment by spectria-limina** [comment] 2024-12-12 02:08
You're correct. [This has now largely been fixed](https://github.com/rust-lang/reference/issues/565#issuecomment-778660037).

There is one remaining sensitivity to execution ordering: one derive can emit `use` items that bring another into scope, to "save" a subsequent derive that would otherwise have been an error. This is an extremely obscure case, but it is technically possible. If the attributes are reordered then, and only then, could this produce an error where previously there was none.

That said, this case is:
1. **Well-defined:** The situation that gives rise to it is clearly understood and quite precise.
2. **Unlikely to arise by accident:** Derives generally don't emit `use` to begin with, and there are additional conditions required before they could hit this.
3. **Has basically no valid use case:** There's nothing you can do by saving a non-imported derive that you can't already do in better ways.
4. **Not going to produce subtle bugs:** It's always a hard error or nothing. This can't *change* the interpretation of any future `Derive`, because it's an error for a macro to change the result of another macro's name resolution other than from "Not found" to "found", even retroactively.
5. **Easily fixed:** Simply import the `Derive` properly.

All of these combinations together make it an excellent candidate, IMO, for a lint with an aim of turning it into a hard error.

**Comment by maksym-arutyunyan** [comment] 2025-06-08 06:50
Thanks for the explanation, @spectria-limina — it’s great to know the remaining edge case is rare, well understood, and easily fixed.

Since this seems no longer a blocker, I’m hopeful rustfmt could support a consistent derive order in the future. It would really help users adopt a common style and avoid fragmentation across tools.

Could you please **reopen this issue**, or point to a new one if it’s being tracked elsewhere?

**Comment by spectria-limina** [comment] 2025-06-08 10:56
I would love to reopen this, but I lack permissions to do that.

**Comment by calebcartwright** [comment] 2025-06-11 20:21
I don't think it's accurate to say this is no longer a blocker. This has always been a situation where problems wouldn't occur in the majority of cases, but they could occur in a small number of cases. So even if/when the small number of cases gets smaller, that doesn't change the underlying fact that problems could occur.

I'll label this so it gets in the queue for the style team to discuss in a future meeting though

**Comment by maksym-arutyunyan** [comment] 2025-06-11 21:14
Thanks @calebcartwright!

I opened the new issue https://github.com/rust-lang/rustfmt/issues/6574 because I wasn’t sure whether this one could be reopened — feel free to handle them however you think is best.

My main goal was to summarize the progress since 2017 and show that there’s ongoing interest from users. Even a partial solution — sorting only common, well-behaved derive traits — would already be a big improvement for many of us.

Appreciate you nominated this for discussion!
